### ISSUE TITLE
change name of zero-length dataobject to ｈåϻѕàｌâｄ and it becomes unusable

### ISSUE THREAD

**Issue by kellerb** [DICE-UNC/irods-cloud-browser#109]
Used the following site to create a unicode string:
http://www.geertvanderploeg.com/unicode-gen/

input: `hamsalad`
output: `ｈåϻѕàｌâｄ`

Used `Rename` button to rename dataobject to: `ｈåϻѕàｌâｄ`

Can no longer go to info view or download data object

**Comment by michael-conway** [comment]
in testing with iRODS recent versions this works fine.  I want to put this down to the fact that the dfc1 test grid is iRODS 4.0.  We will add this to our testing once we have testing.
