### ISSUE TITLE
recursive re-listing of non-existent directory when file not found

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-cloud-browser#112]
Delete the home dir for a user, login to my home then repeatedly, recursively generates file not found and attempts to get to file.

Instead we need to substitute a file not found page (not message) when clicking on a subdir instead of resetting to a location, this can show in the main browser center pane and allow alternative navigation selections, perhaps showing a breadcrumb to the path they were trying to go to.

**Comment by llchristopherson** [comment]
We don't worry about bad breadcrumbs at this point. Will worry about them in 1.1.
