### ISSUE TITLE
Can't read a file across federation with strict ACLs, even though user has permission

### ISSUE THREAD

**Issue by beppodb** [DICE-UNC/irods-cloud-browser#116]
zoneA and zoneB are federated. ACLs are strict in both zones.

alice#zoneA performs:
ichmod -r read bobby#zoneB /zoneA/home/alice

With iCommands, bobby#zoneB (through zoneBicat) can navigate to /zoneA/home/alice and view/download files.

With Cloud Browser, bobby doesn't see alice in /zoneA/home. However, bobby can trick Cloud Browser by appending %2Falice to the URL in the address bar. At that point, bobby can see the files in /zoneA/home/alice . However, once bobby clicks info or attempts to download the file, "file not found" appears, and bobby is returned to /zoneB/home/bobby.

**Comment by michael-conway** [comment]
Is this using the code on the dfc test lab?  

We have a general issue at #113 that this may a duplicate of, let's park this one and address 113 and retest...

**Comment by beppodb** [comment]
Uses the code on the dfc test lab, but different EC2 instances. I will re-test how and when ever you like.

**Comment by michael-conway** [comment]
OK I do think that this is fixed, Reagan ran into similar issues, it had 
to do with the iRODS path having a # in it an it not being url encoded

eg user#zone came across as user and dropping the zone
