### ISSUE TITLE
Missing documentation on PAM setup

### ISSUE THREAD

**Issue by burnce** [DICE-UNC/irods-cloud-browser#126]
Hello,

I have encountered the following problem. I set all the presets in the groovy file to point to my iRODS server using PAM authentication. The iRODS server however refuses the connection due to:

    ERROR: sslAccept: error calling SSL_accept. SSL error: error:14094416:SSL
    routines:SSL3_READ_BYTES:sslv3 alert certificate unknown

How do I point the cloud browser to the correct certificate?

Thanks,

Bernhard

**Comment by michael-conway** [comment]
It's likely that you are using a self-signed SSL certificate.  The issue 
is that the public key is not in your keystore.

The JVM on which you are running Tomcat or another web server needs that 
SSL key imported, which is done using the keytool command. There is a 
good reference here:

http://alvinalexander.com/java/java-using-keytool-import-certificate-keystore

That should resolve your issue.

Cheers
MC

**Comment by burnce** [comment]
Hello Mike,

Thanks for the prompt reply Mike,

Adding the CA certificate which signed the iRODS server certificate ti the tomcat-server jvm's keystore worked.

Cheers,

Bernhard

**Comment by michael-conway** [comment]
OK great.  Yes, the SSL stuff is a pain, especially with self signed 
certs.  For the cyberduck folks, we've added the ability to bypass 
checks through a property, as well as inject a custom trust manager, so 
I'm going to merge that jargon code into the web interface in this next 
mx release.

We've had more SSL headaches than anything!

Cheers
MC
