### ISSUE TITLE
Passwords showing in plaintext with PAM auth

### ISSUE THREAD

**Issue by mcoonen** [DICE-UNC/irods-cloud-browser#127]
I noticed that plain text usernames and passwords are showing up in the catalina.out log-file when iRODS Cloud Browser is configured for PAM-authentication:

/var/log/tomcat7/catalina.out:
    2015-11-23 11:13:48,684 [http-bio-8080-exec-4] DEBUG connection.IRODSMidLevelProtocol  - calling irods function with:<authPlugReqInp_PI><auth_scheme_>PAM</auth_scheme_>
<context_>a_user=MY_USERNAME;a_pw=MY_PASSWORD;a_ttl=0</context_>

**Comment by michael-conway** [comment]
thx that's a jargon patch that didn't make it to the version used by the 
browser, patching now will do a new dot release this morning

MC

**Comment by michael-conway** [comment]
redownload .war file and install for the backend

https://github.com/DICE-UNC/irods-cloud-browser/releases/tag/1.0.0-RELEASE

This was an update to the jargon library.

**Comment by mcoonen** [comment]
Thank you for following up so quickly :+1:

**Comment by michael-conway** [comment]
that was not good!  Thanks for catching it.  I had seen in in 4.0.2.4, 
but the cloud browser is actually using a different feature branch that 
we have, but are not really advertising yet to API users, as a few 
things need to be sewn up first.  I had failed to merge that patch into 
the 4.0.3.1 branch.
