### ISSUE TITLE
Metadata search/virtual collections

### ISSUE THREAD

**Issue by beppodb** [DICE-UNC/irods-cloud-browser#134]
From user feedback:
* [We would like to see the interface presented such that] multiple metadata constraints can be entered at once.
* Hot-linked data objects (i.e., objects presented in search results are clickable) would be important to us.
* To give you an idea of the types of searches we would be interested in doing, please take a look at the following iquest commands:
```
iquest "SELECT COLL_NAME, DATA_NAME WHERE META_DATA_ATTR_NAME ='Project' AND META_DATA_ATTR_VALUE ='TEST' AND META_DATA_ATTR_NAME ='Study nickname' AND META_DATA_ATTR_VALUE ='heartbeat' AND META_DATA_ATTR_NAME ='File format' AND META_DATA_ATTR_VALUE ='Comma separated values'"
 
iquest "SELECT COLL_NAME, DATA_NAME WHERE META_DATA_ATTR_NAME ='Study nickname' AND META_DATA_ATTR_VALUE in('sandcastle','heartbeat') AND META_DATA_ATTR_NAME ='File format' AND META_DATA_ATTR_VALUE ='Comma separated values'"
```
* The “in()” clause is important to us, but if it would lead to delay in release, we could initially do without.
* A dropdown list for META_DATA_ATTR_NAME... would be very useful for us as well.
* I’d like to see a list of objects based on some part of the file name or based on a date (older than 5 years, etc). (i.e., system metadata)

**Comment by burnce** [comment]
Very much looking forward to seeing this feature

**Comment by michael-conway** [comment]
this is enough to qualify as a first feature drop.  We'll be expanding this for the 1.0.2 and 1.0.3 milestones!
