### ISSUE TITLE
PAM Authentication - SSL errors

### ISSUE THREAD

**Issue by jay-widernet** [DICE-UNC/irods-cloud-browser#140]
I am able to connect to my DataGrid via standard authentication but when I try to use PAM I receive an authentication error and the following error in my irods log:
```
ERROR: sslAccept: error calling SSL_accept. SSL error: error:140760FC:SSL
routines:SSL23_GET_CLIENT_HELLO:unknown protocol
```
PAM authentication over SSL works just fine via icommands.

**Comment by michael-conway** [comment]
can you do a java -version?  It can be related to the java version you 
are on.  If you are over at Manning I can take a look with you today or 
tomorrow.

You can email me direct.

Cheers
Mike Conway

**Comment by jay-widernet** [comment]
Upgrading from Java 7 to Java 8 has resolved my issue.

Thanks!

**Comment by michael-conway** [comment]
Thanks! Yes, I think the upgrades of OpenSSL due to well-known security 
issues are involved.
