### ISSUE TITLE
Create new collection

### ISSUE THREAD

**Issue by burnce** [DICE-UNC/irods-cloud-browser#143]
Currently I am unable to find the control to create a collection. Does it exist?

**Comment by rwmoore** [comment]
In the iRODS cloud browser, there is a trail of "bread crumbs" that lists the collection hierarchy at the top of the file/collection list.
The last collection in the list has a pull down menu, which includes an action to create a directory.

Reagan Moore

**Comment by burnce** [comment]
Got it, thanks :)
