### ISSUE TITLE
Client side SSL configuration

### ISSUE THREAD

**Issue by redsox38** [DICE-UNC/irods-cloud-browser#150]
I'm getting "Authentication error, check host, port, and login information" in the client when trying to authenticate to a server that requires SSL to connect.  I've imported the server's  intermediate certificates into the java keystore but it doesn't seem to have changed the error that I receive.  On the irods server I see

Mar 31 13:40:04 pid:107553 ERROR: [-]   iRODS/server/core/src/rodsAgent.cpp:222:main :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message []
        [-]     iRODS/server/core/src/irods_server_negotiation.cpp:152:client_server_negotiation_for_server :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [SSL is required by the server but not requested by the client]

How can I configure irods-cloud-browser to require ssl?

**Comment by michael-conway** [comment]
will merge in with install notes issue, this is a config issue.
