### ISSUE TITLE
Installation Clarity

### ISSUE THREAD

**Issue by katbeaulieu** [DICE-UNC/irods-cloud-browser#162]
Hi there,
I'm a little new to working with deploying webapps such as yours so could you provide some clarification on the installation instructions? 

1. Deploy back-end
I went to http://localhost:8080/manager and deployed the irods-cloud-backend.war file which is in my Downloads folder. Do I have to deploy this from another folder location?

2. Deploy front-end
Does this mean I should copy the irods-cloud-frontend folder to my /var/www/html apache2 folder?

3. Optional Proxy
I have tried to do this, but I think this may be causing problems. Here is what I have done to try and configure this:
Edited server.xml (in /etc/tomcat7)
Ran command: sudo a2enmod proxy proxy_ajp
Added the code snippet suggested to apache2.conf
After this I couldn't restart apache2 so I added to apache2.conf the line: ServerName: (myownhostname)
Successfully restarted apache2

4. Configure front-end to back-end
I couldn't figure out what the http address of the backend is so I assumed it was localhost (sorry, it's probably obvious..) so I changed that one line to:
var HOST = "http://localhost:8080/irods-cloud-backend/";

5. Configure browser presets.
 I skipped this because I didn't know if it needed to be right in etc or in some subfolder.

6. Restarted apache2
Tried to access the sites using http://localhost:8080/irods-cloud-frontend but got an HTTP Status 404 error. When I run http://localhost:8080/irods-cloud-backend though, I get a black screen with an orange label at the top that says "Your brand here".

I would really appreciate any help you can give in helping set this up.

**Comment by katbeaulieu** [comment]
Update: I removed the <VirtualHost> code snippet from apache2.conf and changed var HOST to http://localhost/irods-cloud-backend/. To get to the website I put in http://localhost/irods-cloud-frontend which resulted in this screen:
![selection_001](https://cloud.githubusercontent.com/assets/19346775/15252556/7fff39e0-18fc-11e6-86c9-047644af5ce3.png)

**Comment by katbeaulieu** [comment]
Last Update: Seems to be working now, changed the var HOST to http://localhost:8080/irods-cloud-backend. Although I was wondering if there was search functionality somewhere?

**Comment by chexare** [comment]
Hello katbeaulieu, seems like you found your way around, but let me ask you, what version of the CB did you deployed? Our first release did not include any search capabilities, but we are about to cut another release really soon and it will include metadata search, file editing and rule execution.
If you have any more questions please don't hesitate to keep posting.

**Comment by katbeaulieu** [comment]
Hi chexare, I deployed version 1.0.1 of CB.

**Comment by michael-conway** [comment]
there is a new beta available to help address these sorts of issues. Instead of two pieces, you can just drop the pre-built war file into tomcat and forgo all the configuration.  If you are interested you can find the release here: https://github.com/DICE-UNC/irods-cloud-browser/releases/tag/1.0.2.0-beta1
