### ISSUE TITLE
Cannot save text files with new Cloud Browser

### ISSUE THREAD

**Issue by rsplinter** [DICE-UNC/irods-cloud-browser#168]
I have installed the latest Cloud Browser, v1.0.1, now when I try to create a text file 

![700553fa-b180-4c52-8c57-8919c4b2de37](https://cloud.githubusercontent.com/assets/17439874/16529933/7191c252-3f93-11e6-827e-62c60702b23e.png)

Metadata searches also never show a result. I am running CentOS 6.7 with

[root@minrod ~]# rpm -qa | grep irods
irods-icat-4.1.8-0.x86_64
irods-database-plugin-postgres-1.8-0.x86_64
irods-runtime-4.1.6-0.x86_64

I made no changes to any of the configuration files from 1.0 so I am not sure what is going on here.

**Comment by chexare** [comment]
We tested this on our side and is working properly, there might be some configuration issues on your side, did you get rid of the previously deployed .war file and deployed the new one?

**Comment by chexare** [comment]
Closing as a config issue, if your problem persist, please reopen this issue.
