### ISSUE TITLE
Adopt standard DFC color scheme

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-cloud-browser#17]
Adopt standard dfc color scheme to interface
![img_0438](https://cloud.githubusercontent.com/assets/1097261/8754066/d5b3e8aa-2c8e-11e5-89f5-7b72c6f13791.JPG)
![img_0439](https://cloud.githubusercontent.com/assets/1097261/8754071/d9b0baaa-2c8e-11e5-9daa-416cdfb9e4d2.JPG)

**Comment by michael-conway** [comment]
see https://github.com/DICE-UNC/irods-cloud-browser/wiki/Color-Codes

**Comment by llchristopherson** [comment]
Cesar says he will implement today (2015.07.24)

**Comment by chexare** [comment]
New color scheme applied.
