### ISSUE TITLE
irods-cloud-backend-config.groovy is not being used after upgrade from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by jkhodges** [DICE-UNC/irods-cloud-browser#171]
After upgrading the irods cloud browser backend to version 1.0.1 it no longer seems to be using the irods-cloud-backend-config.groovy file.  The login screen shows all fields.  I have checked and rechecked the file permissions and file contents.  Any suggestions?

I completely removed the old backend .war file and webapps directory before upgrading.

**Comment by jkhodges** [comment]
Nevermind....  I found it belongs in /etc/irods-ext now and not just /etc.

**Comment by michael-conway** [comment]
I will check this but I think the configuration was standardized to be
under /etc/irods-ext.  Make sure it is under irods-ext and I will follow up

**Comment by burnce** [comment]
I recall experiencing the same issue.
