### ISSUE TITLE
Metadata Search Browse Option

### ISSUE THREAD

**Issue by katbeaulieu** [DICE-UNC/irods-cloud-browser#172]
What is the browse option supposed to do when you click on the little folder icon for the metadata search page? When I click on this it just gives me a darker page.

**Comment by michael-conway** [comment]
The metadata query is a 'first look' feature, so the visual aspects are 
not quite finished, I understand the confusion.

We were playing with a bar on the left hand side that I think will go 
away.  The idea is that there are many 'views' the cloud browser can 
show, like browsing the hierarchy, doing different kinds of queries, 
managing the delayed rules queue, etc.

In the current version, that bar shows two primary views

  - browse (the folder icon) shows the file browser view
- search(the magnifying glass) takes you to the metadata query view.  
That will be replaced in the next version with a sort of 'app' page that 
can show different types of query builders.

When you go to metadata query, you build your criteria, and then when 
you pick search, it actually runs the query and takes you to the result 
page, that result page is actually the same as the browse page, your 
query is highlighted as a temporary collection.  The way this works is 
that, as we build new ways of querying the data, you can save the 
queries, re-edit them, reexecute them, and if you like them, you can 
save them as a permanent collection. This is the concept of a 'virtual 
collection'.

In this way, you have one browse view, and the folders you browse can be 
the iRODS hierarchy, or they can be collections that come from your 
query, and can actually be data from multiple places, even multiple 
zones.  The query can be an iRODS query, an elastic search query, a 
SPARQL search, etc.  In this way iRODS collections can be formed even 
using an external index, and appear and behave as if they are really all 
in one place.

The short answer is that when you pick the folder, you leave the query 
view and go back to the normal iRODS browse view.  We'll be looking at 
how to rearrange that main page to make that clearer.

Hope that helps!
MC

**Comment by katbeaulieu** [comment]
Thanks for the detailed answer! The new release looks great by the way!
