### ISSUE TITLE
tabs malformed under 'new' war deploy

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-cloud-browser#179]
see issue2-gulp branch.  Select a data object and go to info page.  See screen shot attached
![screenshot from 2016-08-10 13-38-45](https://cloud.githubusercontent.com/assets/1097261/17564032/f9c9602c-5eff-11e6-932c-4ef2243347c2.png)

**Comment by matt1123** [comment]
Fixed with latest commit.
