### ISSUE TITLE
Starred-DatesFileSizes

### ISSUE THREAD

**Issue by llchristopherson** [DICE-UNC/irods-cloud-browser#41]
Applies to all pages. See pdf.
[Starred-DatesFileSizes.pdf](https://github.com/DICE-UNC/irods-cloud-browser/files/1033/Starred-DatesFileSizes.pdf)

Adding to this on 7/31/15:
Is the date last modified? Created? Need headers please.

**Comment by michael-conway** [comment]
fixed, need to grails clean and refresh-dependencies to see fixes.

Issue still requires headers in interface.  Note that both created and modified dates are available
