### ISSUE TITLE
Login-Host

### ISSUE THREAD

**Issue by llchristopherson** [DICE-UNC/irods-cloud-browser#49]
See pdf
[Login-Host.pdf](https://github.com/DICE-UNC/irods-cloud-browser/files/1075/Login-Host.pdf)

**Comment by llchristopherson** [comment]
This will work on the production server.

**Comment by llchristopherson** [comment]
Reopening - add a tooltip over the login host value to provide an example

**Comment by chexare** [comment]
Issue resolved in commit 1d2b64c715c063786f921d64704ca9b68590ed8e
