### ISSUE TITLE
Home-HierarchicalDisplay

### ISSUE THREAD

**Issue by llchristopherson** [DICE-UNC/irods-cloud-browser#55]
Applies to all pages. See pdf.
[Home-HierarchicalDisplay.pdf](https://github.com/DICE-UNC/irods-cloud-browser/files/1079/Home-HierarchicalDisplay.pdf)

**Comment by michael-conway** [comment]
we discussed this one.  Virtual Collections do not have a hierarchical relationship.  I think we should close this, and I'm sure we'll have continued discussions on how to better portray virtual collections going forward.
