### ISSUE TITLE
Comments on the name of the tool

### ISSUE THREAD

**Issue by llchristopherson** [DICE-UNC/irods-cloud-browser#59]
I've received comments on the name of the tool: Clouser.

One person thought it was pronounced "clo user"
Another thought it was misspelled "clowser"

The metaphor is not coming through. So we should discuss what DFC wants here.

**Comment by michael-conway** [comment]
the name should just be irods-cloud-browser with a hook for branding

**Comment by michael-conway** [comment]
put proper DFC Cloud Browser title on...we should probably add the DFC logo as well.
