### ISSUE TITLE
'buttons' for responsive actions are not clickable

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-cloud-browser#73]
When you get a collection view as below, clicking on the collection and selection actions has no effect

![image](https://cloud.githubusercontent.com/assets/1097261/9138362/41cdcef8-3cf1-11e5-86ff-5a76c3d91734.png)

**Comment by chexare** [comment]
Resolved. Commit ab8e53156b390b1f28f31c6dbfea4bbb6a5d6823
